# Tensorflow2.0 小练习

In [2]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [3]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########

    # 把输入统一转成 tf.Tensor 格式（以防万一传入的是 numpy 数组）
    x = tf.convert_to_tensor(x)
    
    # 数值稳定性 Trick：找到每一行的最大值，并减去它，防止 tf.exp() 指数爆炸
    x_max = tf.reduce_max(x, axis=-1, keepdims=True)
    safe_x = x - x_max
    
    # 使用纯 tf 算子计算 softmax
    exp_x = tf.exp(safe_x)
    prob_x = exp_x / tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [4]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    x = tf.convert_to_tensor(x, dtype=tf.float32)
    prob_x = 1.0 / (1.0 + tf.exp(-x))
    
    ##########
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [9]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    # 动态获取 x 的数据类型 (float64)，让 label 和它保持一致
    prob = tf.cast(x, x.dtype) 
    label = tf.cast(label, x.dtype)
    
    eps = tf.constant(1e-12, dtype=prob.dtype)
    loss = tf.reduce_mean(tf.reduce_sum(-label * tf.math.log(prob + eps), axis=-1))
    ##########
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [ ]:
def sigmoid_ce(x, label):
    ##########
    '''实现 sigmoid 交叉熵loss函数， 不允许用tf自带的sigmoid_cross_entropy函数'''
    # 动态获取类型，防止 float32 和 float64 冲突
    prob = tf.cast(x, x.dtype)
    label = tf.cast(label, x.dtype)
    
    eps = tf.constant(1e-12, dtype=prob.dtype)
    
    # 完整的二元交叉熵公式
    loss = tf.reduce_mean(-label * tf.math.log(prob + eps) - (1.0 - label) * tf.math.log(1.0 - prob + eps))
    ##########
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 0. 1. 1. 1. 1. 0. 0. 0. 1.]


np.True_